services:
  - type: web
    name: nextcar-dashboard-api
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: echo "DATABASE_URL=$DATABASE_URL" && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: nextcar-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://tu-frontend.vercel.app
      - key: CLOUDINARY_CLOUD_NAME
        value: ''
      - key: CLOUDINARY_API_KEY
        value: ''
      - key: CLOUDINARY_API_SECRET
        value: ''
    healthCheckPath: /health

databases:
  - name: nextcar-db
    databaseName: nextcar
    user: nextcar
    plan: free
    region: oregon
