#!/bin/bash

echo "🚀 Configurando Supabase para el proyecto NEXTCAR Dashboard"
echo ""

echo "📋 Pasos para completar la migración a Supabase:"
echo ""
echo "1. Ve a https://supabase.com y crea una cuenta"
echo "2. Crea un nuevo proyecto"
echo "3. Ve a Settings > Database"
echo "4. Copia la 'Connection String' (URI format)"
echo "5. Actualiza el archivo .env con tu DATABASE_URL real"
echo ""
echo "Ejemplo de DATABASE_URL:"
echo "DATABASE_URL=\"postgresql://postgres.[ref]:[password]@aws-0-[region].pooler.supabase.com:6543/postgres\""
echo ""
echo "6. Ejecuta: npm run db:migrate"
echo "7. Ejecuta: npm run db:seed"
echo ""
echo "✅ Una vez configurado, tu aplicación usará Supabase como base de datos!"
